name: Fetch and Clean OpenPhish Feed

on:
  schedule:
    - cron: '0 0,12 * * *' # Runs automatically every day at midnight
  workflow_dispatch: # Allows manual triggers

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Download and Clean OpenPhish Feed
      run: |
        # Download data, forcing curl to follow HTTP redirects (-L)
        curl -sSL "https://githubusercontent.com" -o raw_list.txt || curl -sSL https://openphish.com/feed.txt -o raw_list.txt
        
        # Strip protocols out
        sed -e 's~http://~~g' -e 's~https://~~g' raw_list.txt > edl-list.txt
        
        # Clean up files
        rm -f raw_list.txt

    - name: Commit and Push Cleaned List
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add edl-list.txt
        git commit -m "Automated update: Cleaned OpenPhish EDL" || exit 0
        git push
